services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: pluralsight
      POSTGRES_PASSWORD: pluralsight
    ports:
      - '5432:5432'
  events:
    image: events-service:0.0.1-SNAPSHOT
    depends_on:
      - postgres
      - mongo
    environment:
      - "SPRING_PROFILES_ACTIVE=docker-event-service"
    ports:
      - '8081:8081'
  registration:
    image: registration-service:0.0.1-SNAPSHOT
    depends_on:
      - postgres
      - mongo
      - events
    environment:
      - "SPRING_PROFILES_ACTIVE=docker-registration-service"
    ports:
      - '8080:8080'