server:
  port: 8081
spring:
  data:
    mongodb:
      host: mongo
  datasource:
    url: jdbc:postgresql://postgres:5432/pluralsight
    username: pluralsight
    password: pluralsight
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

tickets:
  events:
    url: http://events:8081

management:
  endpoints:
    web:
      exposure:
        include: health,env,beans,conditions,mappings,loggers,metrics
    endpoint:
      health:
        show-details: always
      env:
        show-values: always
